---
- name: Add Flathub remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
    method: system

- name: Install Flatpak apps
  become: true
  community.general.flatpak:
    name:
      - com.google.Chrome
      - com.visualstudio.code
      - com.slack.Slack
      - us.zoom.Zoom
      - com.spotify.Client
    state: present
    method: system
