---
- name: Terminal apps
  import_playbook: terminal-apps.yml

- name: Terminal config
  import_playbook: terminal-config.yml

- name: Desktop apps
  import_playbook: desktop-apps.yml

- name: Desktop config
  import_playbook: desktop-config.yml
